# Generated by Django 4.2.29 on 2026-03-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('capacidad', models.IntegerField()),
                ('tipo', models.CharField(choices=[('puesto', 'Puesto'), ('sala', 'Sala')], max_length=20)),
            ],
        ),
    ]
