# Generated by Django 4.2.29 on 2026-03-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_rol_alter_user_suscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='user',
            name='suscripcion',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='standard', max_length=20),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.DeleteModel(
            name='Suscripcion',
        ),
    ]
