# Generated by Django 4.2.30 on 2026-05-02 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_subscription_subscriptionhistory'),
        ('users', '0006_user_subscription_cycle_fields'),
    ]

    operations = [
    ]
