# Generated by Django 4.2.30 on 2026-05-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20260502_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='standard', help_text='Plan de suscripción (standard / premium / enterprise). En la app, enterprise se muestra como SuperPro. No hay otro modelo de suscripción.', max_length=20),
        ),
    ]
